In [5]:
# og_train_path = '/local_hdd/works/ICRyu_workspace/for_yolo/train/novacos'
# save_train_path = '/local_hdd/works/ICRyu_workspace/for_yolo/train/novacos'
# save_validation_path = '/local_hdd/works/ICRyu_workspace/for_yolo/train/novacos'
og_train_path = '/local_hdd/works/ICRyu_workspace/for_yolo/train/spocado'
save_train_path = '/local_hdd/works/ICRyu_workspace/for_yolo/train/spocado'
save_validation_path = '/local_hdd/works/ICRyu_workspace/for_yolo/train/spocado'

In [6]:
train_og_file_name = 'yolov4_spocado_ryu_v01_train_og.txt'

In [7]:
import random
import os
import numpy as np
import shutil
from tqdm import tqdm

## train set , validation set 분리 (text 파일)

In [8]:
txt = open(os.path.join(og_train_path, train_og_file_name),'r')
contents = txt.readlines()

random.shuffle(contents)

count = 0
length = len(contents) #total line
split_ratio = 0.1 # 비율 설정.


i = 0
train_cnt = 0

train_file_name = os.path.splitext(train_og_file_name)[0][:-3]
val_file_name = os.path.splitext(train_og_file_name)[0][:-8]+'validation'

f = open(os.path.join(save_train_path, train_file_name + os.path.splitext(train_og_file_name)[1]),'w')
f2 = open(os.path.join(save_validation_path, val_file_name + os.path.splitext(train_og_file_name)[1]),'w')


for line in contents:
    count += 1
    if count < int(length*split_ratio) :
        f2.write(line)
    else :
        train_cnt += 1
        f.write(line)

print(train_cnt)

txt.close()
f.close()
f2.close()

3560


In [11]:
with open(os.path.join(og_train_path, train_og_file_name),'r') as f:
    file_list = f.readlines()




In [15]:
each_file = file_list[100]

In [17]:
os.path.splitext(each_file.replace('\n', ''))[0]+'.txt'

'/local_hdd/works/ICRyu_workspace/for_yolo/dataset/kitti_filtered/006786.txt'

## (파일 자체를 분리)

In [4]:
import random
import os
import numpy as np
import shutil
from tqdm import tqdm

In [5]:
img_path = '/DL_data_big/AI_factory_dataset/tracking_recognition/ai_factory_tracking/dataset/train_img'
img_val_path = '/DL_data_big/AI_factory_dataset/tracking_recognition/ai_factory_tracking/dataset/val_img'
label_path = '/DL_data_big/AI_factory_dataset/tracking_recognition/ai_factory_tracking/dataset/train_label_norm'
label_val_path = '/DL_data_big/AI_factory_dataset/tracking_recognition/ai_factory_tracking/dataset/val_label'

In [6]:
file_list = os.listdir(img_path)
random.shuffle(file_list)

count = 0
length = len(file_list) #total line
split_ratio = 0.1 # 비율 설정.

i = 0

move_files = []

# 옮길 파일 리스트 작성
for each_file in file_list:
    count += 1
    move_files.append(each_file)
    if count >= length*split_ratio:
        break

# 이미지 파일 옮김
for each_file in tqdm(move_files):
    # print(f'{img_path}/{each_file} >> {img_val_path}/{each_file}')
    shutil.move(os.path.join(img_path, each_file), os.path.join(img_val_path, each_file))

# label 파일 옮김
for each_file in tqdm(move_files):
    # print(f'{img_path}/{each_file} >> {img_val_path}/{each_file}')
    file_name = os.path.splitext(each_file)[0]
    file_ext = os.path.splitext(each_file)[1]
    label_file_name = file_name+'.txt'
    shutil.move(os.path.join(label_path, label_file_name), os.path.join(label_val_path, label_file_name))


print()
print(f'{count} files moved')
print('END')


100%|██████████| 1840/1840 [00:01<00:00, 1011.05it/s]
1840 files moved
END



In [18]:
img_path = '/local_hdd/works/ICRyu_workspace/for_yolo/dataset/novacos_filtered'
label_path = '/local_hdd/works/ICRyu_workspace/for_yolo/dataset/novacos_filtered'

In [32]:
names = ['person', 'vehicle', 'twowheeler']

## 라벨 로딩 및 통계

In [9]:
label_file_list = list(filter(lambda x: os.path.splitext(x)[1] == '.txt', os.listdir(label_path)))

NameError: name 'label_path' is not defined

In [22]:
len(label_file_list)

7767

In [43]:
label_data = {}
label_state = {}
for i in names:
    label_state[i] = 0

In [44]:
label_state

{'person': 0, 'vehicle': 0, 'twowheeler': 0}

In [45]:
for each_file in tqdm(label_file_list):
    with open(os.path.join(label_path,each_file), 'r') as f:
        contents = list(map(lambda x: x.split(), f.readlines()))

    each_file_data = np.zeros(len(names), dtype='int8')

    for l in contents:
        class_id = int(l[0])
        label_state[names[class_id]] += 1
        each_file_data[class_id] += 1

    label_data[each_file] = each_file_data

100%|██████████| 7767/7767 [00:00<00:00, 32020.99it/s]


In [46]:
label_state

{'person': 9544, 'vehicle': 21185, 'twowheeler': 1671}

## 라벨 분리하기

In [48]:
split_ratio = 0.1

In [52]:
[k for k, v in label_state.items() if v == min(label_state.values())]

['twowheeler']

In [ ]:
label_data[]

In [63]:
train_label_data = {}
val_label_data = {}

train_label_state = {}
val_label_state = {}
for i in names: train_label_state[i] = 0
for i in names: val_label_state[i] = 0


In [64]:
print('train set state')
print(train_label_state)
print('\nvalidation set state')
print(val_label_state)

train set state
{'person': 0, 'vehicle': 0, 'twowheeler': 0}

validation set state
{'person': 0, 'vehicle': 0, 'twowheeler': 0}


In [ ]:
for each_data in label_data.items():

In [68]:
rand_list = random.shuffle(list(label_data.keys()))

In [ ]:
split_point = split_ratio*len(rand_list)
for i, k in enumerate(rand_list):
    if i <= split_point:
        val_label_data[k] = label_data[k]
    else:
        train_label_data[k] = label_data[k]

In [4]:
import numpy as np

In [38]:
test_a = np.array([0,1,2,0,0,0])

In [39]:
mask = test_a == 0

In [40]:
mask

array([ True, False, False,  True,  True,  True])

In [45]:
test_b = np.array([1,2,3,4,5,6])

In [46]:
test_b[mask]

array([1, 4, 5, 6])

In [52]:
test_c = np.array([[1,1,2], [2,1,2], [3,1,2]])

In [53]:
test_c[:,1]

array([1, 1, 1])

In [59]:
bbox_xywh = np.empty((0, 4), float)

In [64]:
x,y,w,h = 5,6,7,8

In [65]:
bbox_xywh = np.append(bbox_xywh, np.array([[x, y, w, h]]), axis = 0)

In [66]:
bbox_xywh

array([[0., 1., 2., 3.],
       [5., 6., 7., 8.]])

In [70]:
test_1 = np.array([10,1,5,20])

In [71]:
np.argsort(test_1)

array([1, 2, 0, 3])